# Dockerfile.frontend

FROM python:3.10-slim

WORKDIR /ui

# Copy only the requirements for caching
COPY ./ui/requirements.txt .

# Upgrade pip and install dependencies
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy rest of frontend code
COPY ./ui .

# Start the Streamlit app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
