version: "3.9"

services:
  backend:
    build: .
    container_name: keyword_backend
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    restart: always

  frontend:
    build: .
    container_name: keyword_ui
    ports:
      - "8501:8501"
    command: streamlit run ui/app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - backend
    restart: always
